### ISSUE TITLE
How does this differ from pressing "Q" and filtering your own cards in trello?

### ISSUE THREAD

**Issue by dsifford** [HugeThoughts/JustMyTrello#2]
Hi there,

Saw this extension in my news feed and my curiosity got the better of me.

Just curious what difference this extension makes versus just pressing "Q" (one of the default trello keyboard shortcuts)?

Thanks for clarifying 😄

**Comment by AshikNesin** [comment]
Hey @dsifford,

I thought Trello doesn't have that feature (not able to find it in Google Search nor my teammates knows about it)

That's why I build it.

I don't think this extension has any difference than trello shortcut (maybe being more visual)

Thanks for sharing that keyboard shortcut 😀
